<?php


use Rushcon\Controller\HelloController;
use PHPUnit\Framework\TestCase;
use Rushcon\Core\Container;

class CreateControllerTest extends TestCase
{

    protected $DiContainer;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->DiContainer = $this->createMock(Container::class);
    }

 
}
